const INIT_DATA = 'INIT_DATA';
const PILOT_INFO_UPDATE = 'PILOT_INFO_UPDATE';
const SHIP_INFO_UPDATE = 'SHIP_INFO_UPDATE';
const LOCATION_INFO_UPDATE = 'LOCATION_INFO_UPDATE';
const SCANS_INFO_UPDATE = 'SCANS_INFO_UPDATE';

module.exports = {INIT_DATA, PILOT_INFO_UPDATE, SHIP_INFO_UPDATE, LOCATION_INFO_UPDATE, SCANS_INFO_UPDATE};
